name: Npm Publish

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - .github/workflows/npm-publish.yml
  workflow_dispatch:

jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/npm-publish.yml@npm-publish-1.1.0
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    with:
      build-command: "npm run build"
      test-command: "echo 'Tests are temporarily disabled'"
      should-generate-documentation: true
      generate-documentation-command: |
        table_of_contents=$(npx markdown-toc@1.2.0 README.md)
        pattern="(<!-- TABLE_OF_CONTENTS_START -->)[\\S\\s]*(<!-- TABLE_OF_CONTENTS_END -->)"
        replacement=$'$1\n'"${table_of_contents}"$'\n$2'
        npx replace "$pattern" "$replacement" README.md

        git add README.md
        if git diff --staged --quiet
        then
          echo "No changes to commit"
        else
          git config --global user.name 'FreePhoenix888'
          git config --global user.email 'freephoenix888@gmail.com'
          git commit -m 'docs: update README.md'
          git push origin main
        fi
        
        npx typedoc ./src/main.ts --out ./docs
